slam_toolbox:
  ros__parameters:
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"
    scan_topic: "/scan"

    mode: "mapping"          # 온라인 SLAM
    resolution: 0.05
    max_laser_range: 8.0
    minimum_travel_distance: 0.10
    minimum_travel_heading: 0.10
    transform_publish_period: 0.02
    map_update_interval: 1.0

    use_scan_matching: true
    use_scan_barycenter: false
    use_loop_closure: true
    do_loop_closing: true
    loop_search_maximum_distance: 3.0

    use_scan_time: false